version: "3.8"
services:
  app:
    container_name: nestjs_app
    build:
      context: .
      dockerfile: Dockerfile
    environment:
      - PORT=${PORT-3000}
    ports:
      - "${PORT-3000}:${PORT-3000}"
    volumes:
      - .:/usr/src/app
      - /usr/src/app/node_modules
